name: SSH and Docker Deployment
# 手動実行用のトリガー
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  ssh_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      env:
        SSH_KEY: ${{ secrets.switchbot }}  # GitHub Secretsに保存されたSSH秘密鍵

    - name: Debug SSH key and host
      run: |
        echo "SSH_KEY: $SSH_KEY"
        echo "HOST: $HOST"
      env:
        HOST: ${{ secrets.host }}  # GitHub Secretsに保存されたサーバーのホスト名またはIP

    - name: Add SSH host to known hosts
      run: |
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
        cat ~/.ssh/authorized_keys  # known_hostsに追加されたホストの公開鍵を確認する
      env:
        HOST: ${{ secrets.host }}  # GitHub Secretsに保存されたサーバーのホスト名またはIP

    - name: Test SSH connection
      run: |
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_ed25519 $HOST "hostname"
      env:
        HOST: ${{ secrets.host }}  # GitHub Secretsに保存されたサーバーのホスト名またはIP

    - name: Pull latest changes and deploy with Docker
      run: |
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_ed25519 $HOST "
          cd desiccator-monitor && git pull && docker compose up -d
        "
      env:
        HOST: ${{ secrets.HOST }}  # GitHub Secretsに保存されたサーバーのホスト名またはIP

    - name: Check the status of Docker containers
      run: |
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_ed25519 $HOST "
          docker ps
        "
      env:
        HOST: ${{ secrets.HOST }}  # GitHub Secretsに保存されたサーバーのホスト名またはIP
