name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: |
          cd ~/desiccator-monitor
          git pull origin main

      - name: Restart Docker containers
        run: |
          cd ~/desiccator-monitor
          docker compose up -d --build
