name: SSH and Docker Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  ssh_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh && chmod 700 ~/.ssh
        echo "-----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACAXr82M/50dEMgcDxZzLreoR/myIXBMR/ifNZIjL83f0gAAAJhSVaK3UlWi
        twAAAAtzc2gtZWQyNTUxOQAAACAXr82M/50dEMgcDxZzLreoR/myIXBMR/ifNZIjL83f0g
        AAAECqE638J8oZILOkVQ8tg+MqX+F6YEy4jSpoUO5qNesUhxevzYz/nR0QyBwPFnMut6hH
        +bIhcExH+J81kiMvzd/SAAAAEnNrdHltMTUzQGdtYWlsLmNvbQECAw==
        -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH host to known hosts
      run: |
        ssh-keyscan -H 10.30.0.111 >> ~/.ssh/known_hosts  # 直接IPアドレスを指定

    - name: Pull latest changes and deploy with Docker
      run: |
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa yuma@10.30.0.111 "
          cd desiccator-monitor && git pull && docker compose up -d
        "

    - name: Check the status of Docker containers
      run: |
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/id_rsa yuma@10.30.0.111 "
          docker ps
        "
